### ISSUE TITLE
OpenStreetMap Carto changes

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/chef#104]
OpenStreetMap Carto's next release with v3.0.0, which brings some changes to dependencies. The OSMF tile servers meet the difficult ones (Mapnik 3), but some of the others might need minor changes

- Mapnik 3 is required
- CartoCSS 0.16.0 is required and 0.16.3 is suggested
- `project.mml` is no longer a generated file, but passed directly to CartoCSS.

I believe the CartoCSS version change is the only one which the OSMF servers might not already meet.

c.f. gravitystorm/openstreetmap-carto#2473

**Comment by tomhughes** [comment]
We already have mapnik 3 and carto 0.16.3 so that is no problem.

I don't understand the third point because we have never done anything to generate `project.mml` rather we just pass the one that's in the stylesheet repo to carto - was that wrong?

Also, is the v3.0.0 release not going to need a reload of the database? I thought that the major version bump was the point where that was going to happen?

**Comment by pnorman** [comment]
> I don't understand the third point because we have never done anything to generate project.mml rather we just pass the one that's in the stylesheet repo to carto - was that wrong?

Then there's no need to change. project.mml was always a headache because it was a generated file that needed to be in sync with project.yaml

> Also, is the v3.0.0 release not going to need a reload of the database? I thought that the major version bump was the point where that was going to happen?

The schema change will also be a major version increase, just not **this** one. We ended up increasing the required versions first.
