### ISSUE TITLE
Munin Frontend

### ISSUE THREAD

**Issue by trucheromayor** [openstreetmap/chef#228]
Dear collegues,

I have and issue related with the munin sever frontend. Even after a fresh cookbook update and deployment I have the  same error on http://myserver.org/munin 

HTML::Template::param() : attempt to set parameter 'groups' with a scalar - parameter is not a TMPL_VAR! at /usr/share/perl5/Munin/Master/HTMLOld.pm line 695.

This issue is documented in some way here:
https://github.com/munin-monitoring/munin/issues/610

Does anybody have the same issue?

KR

Jon

Jon

**Comment by trucheromayor** [comment]
Dear Tom,
Thanks for your quick response.

In fact I´m deploying an openstreetmap infrastructure with your chef repositories...

**Comment by tomhughes** [comment]
Er... Right. That's a new one... I'm not sure that's something we really want to, or are able to, support.

In any case there's nothing in your report to suggest the problem is anything to do with these cookbooks. Certainly there's no way I could diagnose it without sitting down and debugging it on your server - there's nothing here that I've ever seen before and it sounds like an internal issue in munin.

**Comment by trucheromayor** [comment]
Thank you Tom,

I was just wondering if somebody had the same issue. Coobok used is munin and the cookbook dependencies, networking, ssl and apache.  The deploying is correct on the machine but when I access to munin fronted I get the error:

HTML::Template::param() : attempt to set parameter 'groups' with a scalar - parameter is not a TMPL_VAR! at /usr/share/perl5/Munin/Master/HTMLOld.pm line 695.

OS: Ubunti 16.04
Chef Sever 14

Which are the OS and Chef versions targets of these recipes?
Thank you in any case for your attention.

KR

Jon

**Comment by tomhughes** [comment]
The chef version is not going to be relevant, especially the server version. There is no chef server 14 anyway - the most recent is 12.19.31 currently. Client wise we are running 14.11.21 but as I say that won't be anything to do with this.

We no longer support anything other that Ubuntu 18.04 because that is what all our machines run - that said we did have a 14.04 until fairly recently but I have removed all that support now. Our munin frontend has been running 18.04 for the best part of a year though which is probably what's relevant here.

**Comment by trucheromayor** [comment]
Hi Tom again!!
My apologyzes for the versions confusion. I´m not right now on my computer to check it.   May be we should try to run the recipe in a 18.04 machine... 

Thanks again. I hope I can feedback you soon with the solution...

KR

Jon
